# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
meta:
  engine: 4.1.0
units:
  pu: U + 2
points:
  zones:
    matrix:
      columns:
        outer:
          rows.bottom.skip: true
          rows.top.skip: true
        pinky.key.stagger: 0.3U
        ring.key:
          stagger: 0.66U
          splay: -7
          spread: 1.1U
        middle.key:
          stagger: 0.25U
          splay: -5
          spread: 1.075U
        index.key.stagger: -0.4U
        inner.key.stagger: -0.1U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
      rotate: 12
      anchor:
        # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
        shift: [100, -150]
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.45U, -1.15U]
      columns:
        tucky:
          key.name: thumb_tucky
          key.splay: 0
        reachy:
          key.spread: 1U
          key.splay: -15
          key.origin: [-0.5U, -0.7U]
          key.name: thumb_reachy
outlines:
  keys:
    - what: rectangle
      where: true
      size: [1U, 1U]
  raw:
    - what: rectangle
      where: true
      size: [1pu, 1pu]
  pinky_right:
    - what: rectangle
      where:
        - ref: matrix_pinky_top
          shift: [1.0U, -0.5pu]
      size: [1pu, 2pu]
  ring_right:
    - what: rectangle
      where:
        - ref: matrix_ring_top
          shift: [1.0U, -0.5pu]
      size: [1pu, 2pu]
  thumb_up:
    - what: rectangle
      where:
        - ref: thumb_tucky
          shift: [0U, 1U]
      size: [1pu, 1pu]
  inner_down:
    - what: rectangle
      where:
        - ref: matrix_inner_bottom
          shift: [0U, -0.9U]
      size: [1pu, 1pu]
  combined_raw:
    - name: raw
    - operation: add
      name: pinky_right
    - operation: add
      name: ring_right
    - operation: add
      name: thumb_up
    - operation: add
      name: inner_down
  io_rect:
    - what: rectangle
      where:
        - ref: matrix_middle_bottom
          shift: [0pu, -1U]
          rotate: 0
      size: [4.2pu, 2pu]
  io_fill:
    - what: rectangle
      where:
        - ref: matrix_pinky_bottom
          shift: [0pu, -1U]
          rotate: 0
      size: [1pu, 1pu]
  io_fill2:
    - what: rectangle
      where:
        - ref: thumb_tucky
          shift: [-4pu, 0U]
          rotate: 0
      size: [8pu, 1pu]
  io_patch:
    - name: io_fill
    - operation: intersect
      name: io_fill2
  board:
    - name: combined_raw
    - operation: add
      name: io_rect
    - operation: add
      name: io_patch
      fillet: 0.75
pcbs:
  reversible_split:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: mx
        where: true
        params:
          from: GND
          to: "{{name}}"
          reverse: true
          keycaps: true
          hotswap: true
      mcu:
        what: mcu_nice_nano
        where:
          - ref: matrix_middle_bottom
            shift: [0U, -1.235U]
            rotate: 180
        params:
          reversible: true
          reverse_mount: true
          show_silk_labels: false
          show_via_labels: false
          # right side pins
          P21: matrix_ring_home
          P20: matrix_ring_bottom
          P19: matrix_pinky_top
          P18: matrix_pinky_home
          P15: matrix_pinky_bottom
          P14: matrix_outer_home
          P16: thumb_tucky
          P10: thumb_reachy
          # left side pins
          P1: matrix_ring_top
          P0: matrix_middle_bottom
          P2: matrix_middle_home
          P3: matrix_middle_top
          P4: matrix_index_bottom
          P5: matrix_index_home
          P6: matrix_index_top
          P7: matrix_inner_bottom
          P8: matrix_inner_home
          P9: matrix_inner_top
      battery_connector:
        what: battery_connector_jst_ph_2
        where:
          ref:
            - matrix_middle_bottom
          shift: [0.75U, -1U]
          rotate: 0
        params:
          reversible: true
          BAT_N: GND
          BAT_P: pos
      on_off_switch:
        what: power_switch_smd_side
        where:
          ref:
            - matrix_middle_bottom
          shift: [0.75U, -2.02U]
          rotate: -90
        params:
          reversible: true
          from: pos
          to: RAW
      horizontal_reset:
        what: reset_switch_smd_side
        where:
          ref:
            - thumb_tucky
          shift: [-2.3U, -0.46U]
          rotate: -180
        params:
          reversible: true
          from: GND
          to: RST
      version_text:
        what: utility_text
        where:
          - ref: matrix_middle_bottom
            shift: [-1.2U, -1.8U]
        params:
          reversible: true
          height: 2
          width: 2
          text: "WingSpan v2.0.0"
