# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
meta:
  engine: 4.1.0
units:
  pu: U + 2
points:
  zones:
    matrix:
      columns:
        outer:
          rows.bottom.skip: true
          rows.top.skip: true
        pinky:
        ring.key:
          stagger: 0.66U
          splay: -7
          spread: 1.1U
        middle.key:
          stagger: 0.25U
          splay: -5
          spread: 1.075U
        index.key.stagger: -0.5U
        inner.key.stagger: -0.2U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
      rotate: 12
      anchor:
        # Shift the PCB slightly to the right and down, otherwise it's weirdly positioned outside of the main sheet in KiCad
        shift: [100, -150]
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.75U, -1.25U]
      columns:
        tucky:
          key.name: thumb_tucky
        reachy:
          key.spread: U
          key.splay: -15
          key.origin: [-0.5U, -0.7U]
          key.name: thumb_reachy
    square_center:
      anchor:
        ref: matrix_middle_bottom
        shift: [0.175U, 0.2U]
outlines:
  keys:
    - what: rectangle
      where: -/square_center/
      size: [1U, 1U]
  raw:
    - what: rectangle
      where: -/square_center/
      size: [1pu, 1pu]
  rect:
    - what: rectangle
      where: square_center
      size: [6.85U, 4.3U]
      fillet: 1
  board:
    - name: rect
    - operation: add
      name: raw
      fillet: 0.5
  control:
    - name: board
    - operation: stack
      name: keys
pcbs:
  reversible_split:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      keys:
        what: mx
        where: -/square_center/
        params:
          from: GND
          to: "{{name}}"
          reverse: true
          keycaps: true
          hotswap: true
      mcu:
        what: mcu_nice_nano
        where:
          - ref: matrix_inner_home
            shift: [1U + 1.75, 1U + 3.5]
            rotate: 0
        params:
          reversible: true
          show_silk_labels: false
          # right side pins
          P21: matrix_inner_top
          P20: matrix_inner_home
          P19: matrix_inner_bottom
          P18: matrix_inner_top
          P15: matrix_inner_home
          P14: matrix_index_home
          P16: thumb_reachy
          P10: thumb_tucky
          # left side pins
          P1: matrix_outer_home
          P0: matrix_pinky_top
          P2: matrix_pinky_home
          P3: matrix_pinky_bottom
          P4: matrix_ring_top
          P5: matrix_ring_home
          P6: matrix_ring_bottom
          P7: matrix_middle_top
          P8: matrix_middle_home
          P9: matrix_middle_bottom
      battery_connector:
        what: battery_connector_jst_ph_2
        where:
          ref:
            - matrix_inner_home
          shift: [0.75U, -2]
          rotate: 90
        params:
          reversible: true
          BAT_N: B-
          BAT_P: pos
      on_off_switch:
        what: power_switch_smd_side
        where:
          ref:
            - matrix_middle_top
          shift: [2U, 5.25]
          rotate: 90
        params:
          reversible: true
          from: pos
          to: B+
      horizontal_reset:
        what: reset_switch_smd_side
        where:
          ref:
            - matrix_middle_top
          shift: [1U, 4.75]
        params:
          reversible: true
          from: GND
          to: RST
